[puppet/all] Restore /etc/grid5000 to store environment information

diff --git a/kameleon-g5k/steps/setup/run_orchestrator.yaml b/kameleon-g5k/steps/setup/run_orchestrator.yaml
--- a/kameleon-g5k/steps/setup/run_orchestrator.yaml
+++ b/kameleon-g5k/steps/setup/run_orchestrator.yaml
@@ -4,9 +4,8 @@
 - puppet_path: "/opt/puppetlabs/bin"
 - puppet_local_path: $$kameleon_data_dir/puppet
 - hiera_local_path: $$kameleon_data_dir/hiera
-- git_tag_file: modules/env/files/min/image_versioning/git_tag
 - version_file: modules/env/files/version
-- postinst_file: modules/env/files/min/image_versioning/postinst
+- release_file: modules/env/files/min/image_versioning/release
 - kameleon_repo_name : "default"
 
 
@@ -23,25 +22,18 @@
     - exec_in: tar xfp - -C $$hiera_path
   - exec_in: $$puppet_path/puppet config set hiera_config $$hiera_path/hiera.yaml
 
-# This step is VERY specific to g5k recipes.
-# It extracts last git commit hash from local repo or $HOME/.kameleon.d/repos/$$kameleon_repo_name and store it in $$git_tag_file in the image.
-- set_git_tag:
+# Store G5K environment release information
+- set_release:
+  - exec_in: echo "$${os_release}-x64-$${variant}-$${image_version}" >> $$puppet_build_path/$$release_file
+  - exec_in: echo "$${g5k_postinst_path}" >> $$puppet_build_path/$$release_file
+  # this extracts last git commit hash from local repo
   - pipe:
     - exec_local: |
-        if $(git status &> /dev/null) ; then
-          git log -n 1 | grep commit | head -n 1 | awk '{print $2}';
-        elif $( cd $HOME/.kameleon.d/repos/$$kameleon_repo_name/ && git status &>/dev/null); then
-          cd $HOME/.kameleon.d/repos/$$kameleon_repo_name/ && git log -n 1 | grep commit | head -n 1 | awk '{print $2}';
-        else
-          echo "Error: Kameleon could find git log in local or in $HOME/.kameleon.d/repos/$$kameleon_repo_name/" ;
-        fi
-    - exec_in: cat - >> $$puppet_build_path/$$git_tag_file
-# Same as above, but store version (kameleon global)
+        git rev-parse HEAD 2>/dev/null || echo "Error: Kameleon could find git log in local or in $HOME/.kameleon.d/repos/$$kameleon_repo_name/" ;
+    - exec_in: cat - >> $$puppet_build_path/$$release_file
+# Also store version
 - set_version:
   - exec_in: echo "$${image_version}" > $$puppet_build_path/$$version_file
-# Same as above, but store postinst path to force version increment
-- set_postinst:
-  - exec_in: echo "$${g5k_postinst_path}" >> $$puppet_build_path/$$postinst_file
 
 - run_puppet:
   - exec_in: |
